"""initial migrate

Revision ID: 5366b4a84978
Revises: 
Create Date: 2020-12-19 12:32:13.124717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5366b4a84978'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_user',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_user_username'), 'model_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_model_user_username'), table_name='model_user')
    op.drop_table('model_user')
    # ### end Alembic commands ###
